spring:
  jpa:
    show-sql: true
  flyway:
    clean-disabled: false

app:
  seeding:
    enabled: true

logging:
  level:
    com.overpass.landmarks: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
